apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flipkart-clone
  labels:
    role: flipkart-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecomm-app
      role: flipkart-clone
    matchExpressions:
      - key: version
        operator: Exists
  template:
    metadata:
      labels:
        app: ecomm-app
        role: flipkart-clone
        version: v1
    spec:
      containers:
        - name: flipkart-clone
          image: abhishekbhagat/blog-webapp
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000

